export default [
  "appconfig", //APP系统配置
  "user/sendLoginSms", //APP系统配置
  "user/fastLogin", //APP系统配置
  "user/oAuthLogin", //授权登录
  "user/authRegister", //授权登录
  "blind/getBlindList", //盲盒列表
  "user/getUserInfo", //盲盒列表
  "my/getUserInfo", //用户详情
  "upload/file", //上传
  "user/editUserInfo", //设置用户信息
  "treasure/getRewardList", //设置用户信息
  "treasure/getUpgradeInfo", //设置用户信息
  "my/addUserAddress", //添加用户地址
  "my/editUserAddress", //添加用户地址
  "my/getUserAddress", //添加用户地址
  "my/getUserAddressInfo", //地址详情
  "my/delUserAddress", //地址详情
  "my/getTagListByGroupId", //标签列表
  "my/createFeedBack", //问题反馈
  "recharge/getCoinsExchangeConfig", //问题反馈
  "coins/getChargeConfigList", //问题反馈
  "order/createTransferCoinsOrder", //问题反馈
  "bill/getCapitalRecordList", //问题反馈
  "order/createRechargeOrder", //问题反馈
  "order/createPayConfigCommon", //收银台
  "getPageInfo", //页面说明
  "withdraw/withdrawConfig", //页面说明
  "withdraw/createWithdraw", //页面说明
  "my/getUserCouponList", //获取优惠券
  "treasure/getRewardList", //藏宝图兑换列表
  "treasure/upgradeMap", //藏宝图兑换列表
  "treasure/exchangeReward", //藏宝图奖品兑换
  "blind/getPointBlindList", //藏宝图奖品兑换
  "mapAuth/getRewardList", //图鉴列表
  "mapAuth/exchangeReward", //图鉴列表
  "mapAuth/getMapsAuthInfo", //图鉴详情
  "order/getOrderList", //盒柜列表
  "order/lockGoods", //盒柜列表
  "order/unlockGoods", //解锁商品
  "order/giveGoods", //发起赠送
  "my/getDefaultAddress", //获取用户默认地址
  "my/setDefaultUserAddress", //获取用户默认地址
  "order/deliveryGoodsInfo", //获取用户默认地址
  "user/userAuth", //实名认证
  "upload/file", //实名认证
  "order/deliveryToPay", //发货去支付运费
  "order/resoleGoods", //发货去支付运费
  "order/getOverOrderList", //发货去支付运费
  "order/giveGoodsInfo", //赠送的奖品详情
  "order/giveGoodsInfo", //赠送的奖品详情
  "order/applyOrder", //申请领取奖品
  "order/applyOrderList", //申请领取列表
  "order/sureGiveGoods", //确认赠送
  "order/getGoods", //确认赠送
  "order/doUnDoOrder", //撤销赠送
  "blind/getBlindBoxList", //盲盒/扭蛋机列表
  "blind/getBlindInfo", //盲盒详情
  "blind/collect", //收藏
  "blind/blindRewardRecord", //奖励记录
  "blind/buyBlindGoods", //创建盲盒订单
  "user/getHomePageInfo", //个人页面接口
  "blind/getCollectList", //收藏页面
  "user/getInvitePageInfo", //邀请赚钱
  "user/getInviteRecodeList", //邀请赚钱列表
  "blind/getCollectMessage", //消息列表
  "blind/getRewardList", //奖励列表
  "user/getMpAuthPhone", //奖励列表
  "user/getAgrementById", //协议
  "createCode", //获取key
  "createMainImg", //生成主图
  "createMinor", //生成附图
  "vervifyCode", //验证
  "blind/getMallGoodsDetail", //晶石商品详情
  "blind/getAdDetail", //活动详细
  "blind/getMallRewardList", //获取商城列表
  "blind/getMallGoodsDetail", //根据id查询商品详情
  "blind/exchageMallGoods", //晶石兑换商品
  "blind/getHotSearch", //热门搜索
  "order/queryOrderCommon", //查询订单
  "createQrcode", //生成小程序二维码
  "user/userSign", //实名认证签名
  "order/resoleGoods2", //分解单个
  "blind/selectRewardList", //查询奖品
  "blind/selectRewardHeaders", //查询奖品
  "blind/zhuXiao", //查询奖品
  "blind/getRecord",
  "admin/tide-coin/orders", // 獲取潮幣訂單列表
  "admin/tide-coin/approve", // 審核潮幣訂單
  "admin/tide-coin/upload-qr", // 上傳QR碼
  "admin/tide-coin/records" // 獲取支付記錄
];
